### ISSUE TITLE
this and that

### ISSUE THREAD

**Issue by nemethf** [l7mp/net-debug#1]
In the Dockerfile:
- iproute2 is listed twice in the apt-get command
- wouldn't starting from alpine result in a smaller size?
- I'd like to see 'bmon' added. I use it from time to time.  It's small, simple, and mostly works.

Can you create an automated release process that puts an image into a docker repository? so we could 'docker pull l7mp/net-debug:latest' or something similar.

Thanks a million

**Comment by levaitamas** [comment]
Spot on, @nemethf ! I am happy to let you know that the latest image (v0.5.4) contains `bmon`, and was released via our automated release process. As of the `alpine` version, I will open a new issue for that. PRs welcome. 

Thanks a zillion.
