### ISSUE TITLE
Rebase to Alpine

### ISSUE THREAD

**Issue by levaitamas** [l7mp/net-debug#2]
The current image size is ~200 MB. The image is based on `debian:stable-slim`. A straightforward way to reduce size is to rebase to `alpine`. 

Originally proposed in #1.

**Comment by nemethf** [comment]
The alpine base image reduces the image size from 192MB to 61MB.  However, some packages are only available from edge, one is from edge/testing.  I don't know what that means in terms of stability.  Anyhow, instead of creating a proper PR, I copy here the new Dockerfile for x86_64:
```
FROM alpine:edge

RUN apk add --no-cache \
    bmon \
    bridge-utils \
    curl \
    bind-tools \
    ebtables \
    ethtool \
    iftop \
    iperf \
    iproute2 \
    iptables \
    iputils \
    less \
    nano \
    net-tools \
    nmap \
    procps \
    socat \
    tcpdump \
    traceroute \
    wget

RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing \
    tcpreplay

RUN curl -Lo /usr/bin/websocat \
    https://github.com/vi/websocat/releases/download/v1.11.0/websocat.x86_64-unknown-linux-musl \
    && chmod a+x /usr/bin/websocat

# RUN /usr/sbin/sysctl -w net.ipv4.ip_forward=0

CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"
```

**Comment by levaitamas** [comment]
Awesome! Thanks a zillion, @nemethf! 

As far as I know, Alpine edge matures to next stable release. [[alpine docs]](https://wiki.alpinelinux.org/wiki/Repositories#Release_Branches). I suggest let us wait for Alpine 3.17 (expected to be released in November) before making Alpine the default base image. In the meantime, I introduce a new image tag `alpine`.

**Comment by levaitamas** [comment]
Good news, everyone! The `l7mp/net-debug:alpine` image is available on [Docker Hub](https://hub.docker.com/r/l7mp/net-debug/tags?page=1&name=alpine).
